import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globalStyle.css";
import "sweetalert2/src/sweetalert2.scss";
import { UserProvider } from "@/providers";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gerencie-se",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="shortcut icon" href="/images/favicon.ico" />
      </head>
      <UserProvider>
        <body className={inter.className}>{children}</body>
      </UserProvider>
    </html>
  );
}
